channels:
  - conda-forge
  - bioconda
dependencies:
  - fastp
  - fastqc
  - cd-hit
  - transdecoder
  - blast
  - hmmer
  - seqtk
  - diamond
  - busco
  - omark
  - eggnog-mapper
  - pip
  - snakemake
  - samtools
  - bowtie2
  - rsem
  - bioconductor-edger
  - trinity
  - pip:
    - argparse
    - pyyaml
    - requests
    - tqdm
    - coloredlogs
    - biopython
    - prettytable
