# -----------------------------------------------------------------
# This file is the default configuration of the optDNTRA workflow 
# -----------------------------------------------------------------

# Specify the extension of paired-end reads, e.g. ["_1", "_2"]
reads:

# Path to the Swiss-Prot database for TransDecoder.Predict, if not specified, the wrapper will download it from https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz automatically
swiss_prot:

# Path to the Pfam database for TransDecoder.Predict, if not specified, the wrapper will download it from https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz automatically
pfam_hmm:

# Specify the name of the BUSCO lineage dataset to be used, e.g. eukaryota_odb10
busco_lineage:

# Path to the Omark database, if not specified, the wrapper will download it from https://omabrowser.org/All/LUCA.h5 automatically
omark_database:
